In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
dataset=pd.read_csv("kidney_disease.csv")

In [22]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [23]:
dataset.drop_duplicates(inplace=True)

In [24]:
dataset.duplicated().sum()

np.int64(0)

In [25]:
dataset.isnull().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [26]:
dataset=pd.get_dummies(dataset, drop_first=True)

In [27]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,dm_ yes,dm_no,dm_yes,cad_no,cad_yes,appet_poor,pe_yes,ane_yes,classification_ckd\t,classification_notckd
0,0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,...,False,False,True,True,False,False,False,False,False,False
1,1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,...,False,True,False,True,False,False,False,False,False,False
2,2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,...,False,False,True,True,False,True,False,True,False,False
3,3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,False,True,False,True,False,True,True,True,False,False
4,4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,...,False,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,False,True,False,True,False,False,False,False,False,True
396,396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,False,True,False,True,False,False,False,False,False,True
397,397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,False,True,False,True,False,False,False,False,False,True
398,398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,False,True,False,True,False,False,False,False,False,True
399,399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,False,True,False,True,False,False,False,False,False,True

In [31]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='median')
dataset = pd.DataFrame(imp.fit_transform(dataset), columns=dataset.columns)

In [32]:
dataset

,id,age,bp,sg,al,su,bgr,bu,sc,sod,...,dm_ yes,dm_no,dm_yes,cad_no,cad_yes,appet_poor,pe_yes,ane_yes,classification_ckd\t,classification_notckd
0,0.0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,138.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,7.0,50.0,1.020,4.0,0.0,121.0,18.0,0.8,138.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.0,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,138.0,...,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,3.0,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0
4,4.0,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,138.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395.0,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
396,396.0,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
397,397.0,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
398,398.0,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
399,399.0,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [33]:
dataset.isnull().sum()

id                       0
age                      0
bp                       0
sg                       0
al                       0
                        ..
appet_poor               0
pe_yes                   0
ane_yes                  0
classification_ckd\t     0
classification_notckd    0
Length: 210, dtype: int64